### ISSUE TITLE
SQL query sets non-nilable optional fields to nil

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-library#3423]
```ballerina
import ballerina/io;
import ballerinax/mysql;

type Package record {|
    string NAME;
    string THUMBNAIL?;
|};

configurable string dbHost = "dbHost";
configurable int dbPort = 3306;
configurable string dbUser = "dbUser";
configurable string dbPass = "dbPass";
configurable string db = "db";

public function main() returns error? {
    mysql:Client dbClient = check new (dbHost, dbUser, dbPass, db, dbPort);
    int id = 1;
    Package pkg = check dbClient->queryRow(`SELECT NAME, THUMBNAIL FROM PACKAGE WHERE PACKAGEID=${id};`);
    io:println(pkg);
}
```

Prints
```json
{"NAME":"item1","THUMBNAIL":null}
```

But it should be 
```json
{"NAME":"item1"}
```

Could be fixed with  #3251
Affected version: 2201.1.1

**Comment by niveathika** [comment]
This is the expected behaviour, 
`SELECT NAME, THUMBNAIL FROM PACKAGE WHERE PACKAGEID=${id};`, this query retrieves data for the thumbnail column. The sql module tries to map that data which will lead to TypeMismatchError. Since the data is null while the expected type is string. (Fixed from Update 2)

`SELECT NAME FROM PACKAGE WHERE PACKAGEID=${id};`. This query will result in the following values,
```
{"NAME":"item1"}
```

**Comment by manuranga** [comment]
Provided query doesn't do what I want. I want the name to be present when that NAME is not `null` in the DB.

(Plus, above provided example breaks Ballerina type system, in above recorded `THUMBNAIL` can't never be null, otherwise it can lead to NPE down the line. @warunalakshitha is a runtime fix needed to detect this? It can lead to similar situation to 504 we saw recently.)

**Comment by niveathika** [comment]
There are 2 issues here,
1. I want the name to be present when that NAME is not null in the DB.
    This is fixed with [3251](https://github.com/ballerina-platform/ballerina-standard-library/issues/3251) in Update 2.
    In this case, the name will be present when the NAME is not null and type mismatch error thrown if the results is null

2. Plus, above provided example breaks Ballerina type system, in original recorded THUMBNAIL can't ever be nil.
    This is also fixed with [3251](https://github.com/ballerina-platform/ballerina-standard-library/issues/3251)
    It will be the same behaviour as point 1. If the column is **fetched** and is nil, a type mismatch error will be thrown.

    If the `THUMBNAIL` column is not fetched in the query, the optional field will not be set. However this will not lead to an NPE as accessing the optional field will add the nil type.
    ```
    string? thumbNail = p.THUMBNAIL;
    ```

**Comment by manuranga** [comment]
Still not getting what I want. I want following record type, since that is what makes sense for the input. The frontend is sending `THUMBNAIL` only when it's available.

```ballerina
type Package record {|
    string NAME;
    string THUMBNAIL?;
|};
```
How can I create an instance of it using ballerina sql module that works for all cases? Maybe it's not a bug, but it's a feature.

**Comment by niveathika** [comment]
Just to clarify the request a bit further, the feature you are asking for is,

1. User will fetch n number of fields from the database.
2. If the values fetched contains ()
    - If the field is a mandatory field, of a union type of () - assign the value
    - If the field is a mandatory field with no () union type - throw an error
    - If the field is an optional field  - Not to set the field. (Ballerina will return nil if this field is accessed further in the code)

IMO the last request should not be supported. 

Optional fields are fields that can be either set by the user or now.  In this case if the user has selected that column, it indicates the user wants to populate that field. How can that be overridden universally without breaking the expected behaviour. 

@daneshk WDYT?


In your case, there needs to be 2 types of records, 
```
type PackageData record {|
    string NAME;
    string? THUMBNAIL;
|};
type Package record {|
    string NAME;
    string THUMBNAIL?;
|};
```
Here, PackageData should be used for retrieval as you indicated, since this can of nil type. However, when the data is returned to the user, if it is nil, then the value should not be set.

**Comment by manuranga** [comment]
From an external users point of view, `Package` works perfectly with ballerina http module, both input and output, then why doesn't it work with sql module.

**Comment by niveathika** [comment]
Package will only work with http if the user send the following json,
```
{
   "name": "p1"
}
```

If the user sends the following json, it will fail with type mismatch error.
```
{
   "name": "p1"
   "thumbnail": null
}
```

However, you are asking the sql module to process the second json.

**Comment by manuranga** [comment]
1. I understand the technical difference, but writing a separate record for sql module is not convenient. Supporting this is a useful improvement.

2. I still don't agree this is correct form Ballerina type system point of view, `{"NAME":"item1","THUMBNAIL":null}` is not valid value for the record type.
So the current behavior is anyway a bug, at least it should throw `TypeMismatchError`.

**Comment by niveathika** [comment]
I am getting the error in updater 2 with sql(1.5.1)

<img width="1218" alt="Screenshot 2022-09-27 at 11 13 24" src="https://user-images.githubusercontent.com/27669465/192442441-5c5f0e8e-3db6-433e-b80f-3582106e2dc0.png">

**Comment by manuranga** [comment]
I had the wrong `distribution = ` in ballerina toml, now I am getting the error. Hence removing the bag label.
